# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d639785d6b630bf964f13574e70a2aa4b98ca455d13122f54081731fb2d5d3c67ab60141c607431b2ff3ac678155aab745791e887f0c4950d26de8b9030d7ae9

test:
  secret_key_base: efbfb7ec696f6ed97cb6eabae97e0f5b6ec55577c8db7ed9a33dd647c62519b8b468e13fe945948ee61dba0ffa694ab8704e64beb1ff961a02d2bd2080d2223e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
